# Generated by Django 3.0.8 on 2020-07-22 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200722_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 23, 31, 58, 968465)),
        ),
    ]
