# Generated by Django 3.0.8 on 2020-07-22 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200722_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 22, 18, 34, 37, 697411, tzinfo=utc)),
        ),
    ]
